name: infrawatch
description: "InfraWatch is a modern, responsive React and TailwindCSS frontend template designed for IT professionals, offering real-time monitoring of servers, services, and network links with intuitive dashboards, detailed service views, and customizable alerts."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  fl_chart: ^0.68.0
  shared_preferences: ^2.0.0
  dio: ^5.0.0
  intl: 0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
